site_name: Anupam Sharma
dev_addr: 127.0.0.1:8080
site_url: https://anp-scp.github.io/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    scheme: slate
    primary: black
    accent: blue
  font:
    text: Fira Mono
    code: Fira Code
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
  custom_dir: docs/overrides

nav:
  - index.md
  - publications.md
  - projects.md
  - news.md
  - CV: https://workdrive.zohopublic.in/file/yipkb5e4fad4e58344375bfa67183ed1ed02a
  - Blog:
    - blog/index.md

markdown_extensions: 
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption

plugins:
  - glightbox
  - search
  - blog:
      archive: false
      authors: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  
hooks:
  - recent_post_hook.py
