authors:
  anp-scp:
    name: Anupam Sharma
    description: Creator
    avatar: https://avatars.githubusercontent.com/anp-scp
    url: https://github.com/anp-scp
  AyushShrivstava:
    name: Ayush Shrivastava
    description: Contributor
    avatar: https://avatars.githubusercontent.com/AyushShrivstava
    url: https://github.com/AyushShrivstava