name: mkdocsPublish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.4
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material==9.5.36
      - run: pip install mkdocs-glightbox==0.4.0 
      - run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add CNAME file to gh-pages branch
        run: |
          # Checkout gh-pages branch
          git checkout gh-pages

          echo "anupamsharma.in" > CNAME
          git add CNAME
          
          # Configure git with GitHub Actions bot credentials
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git commit -m "Add CNAME file for custom domain"
          git push origin gh-pages
          echo "CNAME file updated successfully"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}